# Generated by Django 5.0.6 on 2024-05-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0003_alter_siparis_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='hizmet',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
