# Generated by Django 5.0.6 on 2024-05-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0004_hizmet_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banka',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
