# Generated by Django 5.0.6 on 2024-05-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0006_banka_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banka',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
